### PR TITLE
Create russian

### PR DESCRIPTION
**Pull request by DrHesperus**

### CODE REVIEW

**Review by hammertater — APPROVED** [review]
Thanks for translating!

**Comment by hammertater** [comment]
@DrHesperus Sorry, I haven't had time to update the modpack with your translation. I will do it soon!

**Comment by DrHesperus** [comment]
Ok

**Comment by hammertater** [comment]
TreeChop 0.14.5 is posted on CurseForge and includes your translation. Sorry for the wait!

**Pull request merged**
